{
 "title": "Application metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(go_memstats_alloc_bytes, namespace)"
   },
   {
    "name": "pod",
    "query": "label_values(process_resident_memory_bytes, pod)"
   },
   { "name": "interval", "query": "1m,2m,3m,5m,10m,30m,1h" },
   { "name": "quantile", "query": "1,0.99,0.95,0.9,0.75,0.5,0" }
  ]
 },
 "panels": [
  { "title": "App metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Response time quantile per interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(${quantile:raw}, sum(rate(restapi_response_time_bucket[$interval])) by(handler, status, le))",
     "legendFormat": "{{handler}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests average success rate per interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(method, handler) (rate(restapi_requests_total{code=\"200\"}[$interval])) / sum by(method, handler) (rate(restapi_requests_total[$interval])) * 100",
     "legendFormat": "{{method}} - {{handler}} "
    }
   ]
  },
  {
   "title": "RPS average per interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(restapi_requests_total[$interval])) by(handler)",
     "legendFormat": "{{handler}} "
    }
   ]
  },
  { "title": "Go metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "process memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}",
     "legendFormat": "{{pod}} - resident"
    },
    {
     "expr": "process_virtual_memory_bytes{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}",
     "legendFormat": "{{pod}} - virtual"
    }
   ]
  },
  {
   "title": "process memory deriv",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}[$interval])",
     "legendFormat": "{{pod}} - resident"
    },
    {
     "expr": "deriv(process_virtual_memory_bytes{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}[$interval])",
     "legendFormat": "{{pod}} - virtual"
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}",
     "legendFormat": "{{pod}} - bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}[30s])",
     "legendFormat": "{{pod}} - alloc rate"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}",
     "legendFormat": "{{pod}} - stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}",
     "legendFormat": "{{pod}} - heap inuse"
    }
   ]
  },
  {
   "title": "go memstats deriv",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "deriv(go_memstats_alloc_bytes{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}[$interval])",
     "legendFormat": "{{pod}} - bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}[$interval])",
     "legendFormat": "{{pod}} - alloc rate"
    },
    {
     "expr": "deriv(go_memstats_stack_inuse_bytes{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}[$interval])",
     "legendFormat": "{{pod}} - stack inuse"
    },
    {
     "expr": "deriv(go_memstats_heap_inuse_bytes{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}[$interval])",
     "legendFormat": "{{pod}} - heap inuse"
    }
   ]
  },
  {
   "title": "open fds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "open fds deriv",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "deriv(process_open_fds{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}[$interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}",
     "legendFormat": "{{pod}}: {{quantile}}"
    }
   ]
  }
 ]
}